title:        Relateucate
tagline:      "Learning resources form all over, organized by topic."
#url:          http://jeffbaumes.github.io/relateucate
url:          /
author:
  name:       "Jeff Baumes"
  email:      "jeffbaumes@gmail.com"
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
